"""name table

Revision ID: 8e81b5844fe6
Revises: 3512b9e63503
Create Date: 2019-08-14 00:11:20.663097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e81b5844fe6'
down_revision = '3512b9e63503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('POI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('details', sa.String(length=140), nullable=True),
    sa.Column('lat', sa.Float(precision=64), nullable=True),
    sa.Column('lng', sa.Float(precision=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_POI_name'), 'POI', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_POI_name'), table_name='POI')
    op.drop_table('POI')
    # ### end Alembic commands ###
